listOfTables = ['AppMessage',
                'Basf2Module',
                'GlobalTag',
                'GlobalTagPayload',
                'GlobalTagStatus',
                'GlobalTagType',
                'Payload',
                'PayloadContent',
                'PayloadIov',
                'PayloadIovRpt',
]
